dbt_hypermarche:
  target: dev_antoine
  outputs:
    dev_antoine:
      type: snowflake
      threads: 4
      role: BIKESHARE_TRANSFORMER
      warehouse: BIKESHARE_TRANSFORMING_WH
      database: BIKESHARE
      schema: SILVER
      # to add in local vscode developpement
      # account: xxx-xxx
      # private_key_path: "C:/Users/antoi/.ssh/perso_snowflake/key_agiraud_snowflake_ippon_transformer"
      # user: TRANSFORMER_PC_AG_IPPON

    prod:
      # for snowflake dbt-core deployment
      type: snowflake
      threads: 4
      role: BIKESHARE_TRANSFORMER
      warehouse: BIKESHARE_TRANSFORMING_WH
      database: BIKESHARE
      schema: SILVER
