select
    "ID ligne" as id_ligne,
    "ID commande" as id_commande,
    strptime("Date de commande", '%m/%d/%Y')::date as dt_commande,
    strptime("Date d'expédition", '%m/%d/%Y')::date as dt_expedition,
    "Statut commande" as priorite,
    "ID client" as id_client,
    "Nom du client" as client_nom,
    segment as client_segment,
    ville as ville_nom,
    région as ville_region,
    pays as ville_pays,
    "Zone géographique" as ville_zone,
    "ID produit" as id_produit,
    catégorie as produit_categorie,
    "Sous-catégorie" as produit_souscategorie,
    "Nom du produit" as produit_nom,
    replace("Montant des ventes", ',', '.')::numeric as montant_vente,
    quantité::int as quantite,
    replace(remise, ',', '.')::numeric as remise,
    replace(profit, ',', '.')::numeric as profit
from {{ source("hypermarche", "achats") }}
