select
    "ID ligne" as id_ligne,
    "ID commande" as id_commande,
    cast(to_timestamp("Date de commande", 'mm/DD/yyyy') as date) as dt_commande,
    cast(to_timestamp("Date d'expédition", 'mm/DD/yyyy') as date) as dt_expedition,
    "Statut commande" as priorite,
    "ID client" as id_client,
    "Nom du client" as client_nom,
    "Segment" as client_segment,
    "Ville" as ville_nom,
    "Région" as ville_region,
    "Pays" as ville_pays,
    "Zone géographique" as ville_zone,
    "ID produit" as id_produit,
    "Catégorie" as produit_categorie,
    "Sous-catégorie" as produit_souscategorie,
    "Nom du produit" as produit_nom,
    cast(replace("Montant des ventes", ',', '.') as decimal(18, 3)) as montant_vente,
    cast("Quantité" as int) as quantite,
    cast(replace("Remise", ',', '.') as decimal(18, 3)) as remise,
    cast(replace("Profit", ',', '.') as decimal(18, 3)) as profit
from {{ source("hypermarche", "raw_hypermarche_achats") }}
